/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_im_hero_diffpatch_BsDiff */

#ifndef _Included_com_im_hero_diffpatch_BsDiff
#define _Included_com_im_hero_diffpatch_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_im_hero_diffpatch_BsDiff
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_im_1hero_diffpatch_BsDiff_bsdiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_im_hero_diffpatch_BsDiff
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_im_1hero_diffpatch_BsDiff_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
